#!/usr/bin/env python3
"""lists all databases in MongoDB"""

from pymongo import MongoClient

def list_databases():
    """lists all databases in MongoDB"""
    client = MongoClient('mongodb://localhost:27017/')
    return client.list_database_names()